"""Make user fields optional

Revision ID: 7598646c4ba1
Revises: 9ca6637d87e8
Create Date: 2024-04-02 13:23:53.492385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7598646c4ba1'
down_revision: Union[str, None] = '9ca6637d87e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permissions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
